version: '3.7'
services:
  mysql:
    image: mariadb:10
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'azerty'
    volumes:
      - ./bdd/backups:/backups
      - ./bdd/mysql:/var/lib/mysql
      - ./bdd/scripts:/scripts
    networks:
      - internal